FROM ${IMAGE_PARENT}
LABEL maintainer="${MAINTAINER}"

ONBUILD ARG PYTHON_UID
ONBUILD ARG PYTHON_GID
ONBUILD RUN if [ -n "$PYTHON_UID" ] && [ -n "$PYTHON_GID" ]; then \
              echo " ---> Set python uid ${PYTHON_UID} and gid ${PYTHON_GID}"; \
              sed -i "s/^python:x:[0-9]*:[0-9]*:/python:x:${PYTHON_UID}:${PYTHON_GID}:/g" /etc/passwd; \
              sed -i "s/^python:x:[0-9]*:/python:x:${PYTHON_GID}:/g" /etc/group; \
              chown -R python:python /home/python ; fi

ADD rootfs.tar /

COPY etc /etc

RUN chmod +x $(find /etc/service -name run) && \
    ln -s /etc/service/cron /service && \
    chown -R letsencrypt:letsencrypt /etc/letsencrypt

RUN su -c "pip install --user dnspython" letsencrypt

# RUN echo '* * * * * umask 033; echo hi from $USER' >> /var/spool/cron/crontabs/letsencrypt
RUN echo '10 2 21 * * umask 033; /bin/sh /etc/letsencrypt/update.sh 2>> /etc/letsencrypt/update.log' >> /var/spool/cron/crontabs/letsencrypt

CMD ["/bin/s6-svscan", "-s", "-t0", "/service"]
